plugin: aws_ec2
regions:
  - "us-east-1"
keyed_groups:
  - key: tags.Version
  - key: tags.Name
  - key: tags.App
  - key: tags.Role
filters:
  instance-state-name : running
compose:
  ansible_host: public_ip_address

       